name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          docker build -t myapp:${{ github.sha }} .
          docker tag myapp:${{ github.sha }} mydockerhubuser/myapp:${{ github.sha }}
          docker push mydockerhubuser/myapp:${{ github.sha }}

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies and test
        run: |
          npm ci
          npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          ssh -i ~/.ssh/id_rsa deploy@yourserver "docker pull mydockerhubuser/myapp:${{ github.sha }} && docker stop myapp || true && docker rm myapp || true && docker run -d --name myapp -p 80:3000 mydockerhubuser/myapp:${{ github.sha }}"
